[package]
name = "version"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[lib]
name = "version"
path = "src/lib.rs"

[dependencies]
chelps.workspace = true
libc = "0.2.153"

[build-dependencies]
cc = "1.0.97"
bindgen = "0.69.4"
