[package]
name = "sock"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[dependencies]
libc = "0.2.155"
libnss = "0.8.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
